### ISSUE TITLE
The plugin is not using the configured settings

### ISSUE THREAD

**Issue by jonasraoni** [RBoelter/mostViewed#16]
**Describe the bug**
The plugin is not using the configured settings at the scheduled task.

**To Reproduce**
1. Change the value for the days/amount/years setting
2. Check the used value at the scheduled task

**What application are you using?**
OJS 3.3.x

**Comment by jonasraoni** [comment]
@RBoelter Here's the PR for the problem that I had:
- https://github.com/RBoelter/mostViewed/pull/17

**Comment by jonasraoni** [comment]
I can't create a PR for the plugin gallery without the releases. And also, I didn't see this plugin there.

**Comment by RBoelter** [comment]
I'm not sure if I ever published this plugin in the pkp plugin gallery. I built it for my old employer, like all other OJS plugins, but I didn't publish all of them in the gallery. I will create a release package as soon as possible.

**Comment by RBoelter** [comment]
I think these plugins are in the gallery:
https://github.com/RBoelter/announcementsBlock
https://github.com/RBoelter/twitterBlock (I'm not supporting twitter anymore ;-))
https://github.com/RBoelter/citations
https://github.com/leibniz-psychology/openid (I'm not the repository owner anymore and I think it's painful to make this 3.4 ready, PKP should consider implementing OpenId connect auth in their core lib)

**Comment by jonasraoni** [comment]
Okay, I'll close this one 😁

p.s.: I'm not sure if you're already employed again, but I've just suggested your name to the team in case they need another developer, your code is looking clean/modern and you've got a better experience with OJS than most people out there.
