### ISSUE TITLE
Initial code review

### ISSUE THREAD

**Issue by NateWr** [RBoelter/mostViewed#3]
Looks good! Here are some thoughts on an initial code review and test with 3.1.2.

- Is this line used? I don't see the callback method anywhere: https://github.com/RBoelter/mostViewed/blob/master/MostViewedPlugin.inc.php#L9
- Just double-checking: does this cause a PHP Notice if the `mostReadArticles` setting doesn't exist in the database yet?
- Looks like there are some spaces instead of tabs [here](https://github.com/RBoelter/mostViewed/blob/master/templates/mostViewed.tpl#L4-L23).
- Moving the `<style>` just above the content will ensure that the user never sees a flash of unstyled content: https://github.com/RBoelter/mostViewed/blob/master/templates/mostViewed.tpl#L24. 
  - I'd still recommend putting these into a separate CSS file. The styles in the `<style>` tag will be harder to overwrite from a third-party theme.
- Wrong plugin settings name in form id: https://github.com/RBoelter/mostViewed/blob/master/templates/settings.tpl#L12
- Is this code actually working? https://github.com/RBoelter/mostViewed/blob/master/templates/settings.tpl#L6-L8. Usually, in a template, you need to use `{ldelim}` and `{rdelim}` instead of `{` and `}` to prevent smarty from interpreting it.
- Add a README
- PR with some improvements to the English locale: https://github.com/RBoelter/mostViewed/pull/2

I notice that it's not yet working with 3.2. I'll make a separate issue about that.

**Comment by RBoelter** [comment]
> Is this line used? I don't see the callback method anywhere: https://github.com/RBoelter/mostViewed/blob/master/MostViewedPlugin.inc.php#L9
**removed**

> Just double-checking: does this cause a PHP Notice if the mostReadArticles setting doesn't exist in the database yet?
https://github.com/RBoelter/mostViewed/blob/b56dc86c07097b297c2f6940c696848139b2a129/MostViewedHandler.inc.php#L24-L31

> Looks like there are some spaces instead of tabs here. **fixed**

> Moving the <style> just above the content will... **fixed**

> Wrong plugin settings name in form id: **fixed**

> Is this code actually working? **it worked, but I changed it**

>Add a README **done**

>PR with some improvements to the English locale **merged**
